language: node_js
node_js:
- '8'
- '7'
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- yarn lint
- yarn test
notifications:
  slack:
    secure: mG60YrmiCsQa9ORyp1Lri40jgGp6m0Fhwfu12Z4Jo/ZZWE3jvPus59B4SzOqTQ7pzbglKvWz+IH82UpZHiVYpsnNQyG2brZ3/79iF9TjUIgufWzjvg9dX+n82mv00DNP+H2oMoQsrF8z5G0eE6M2v6L0DJMbaVMgG2W2Hv7ObQ0Qszf/cR2w0lOwdSpTmAvhnpmPayUx8qwCfMvF2CGp8MNBO52zNnsZjBJjDBnY1kf9t+ZaHSw0ENzimlx5TdJQPcUvO1aQMrmsbGbHrAeu7Rz6qpvMqUls/iJ4cZN5/9AYh4GICu4Fqhd6p0BmT6FXLN5AoVxnnQx1Yc4zGtc8gvHIZ1FZwpgYtRTJ90rKS5tCiwUumiCCCwa1EJ9ng0eTVuPJQwwkSoS6Zfa+ZkbqdlhGdR7WR1/9xcGshgQCjFz4MyU4pRAdnTrrSdNxBhzmK6DbdilEBSQqhLo/Xcf0p5thHSVbWNs6Du5/WlpG0SAT9h3GIuZttZ7VVzHwLJ2uVfDL53Qk+SOWjAn8h15aOKykoCVIB87NWs8rMynYGJZT85/KhBLteDivQSF5YzNWD5JoyFbpj5Gujn7ql62tJAo+9l5FN/CXE0nQoIl4HhMYol8aiHSPtU4lXwWxC0mDLDpvYA+T8lY5z6W2m+wHf3cYcAZ8g7I0xzDpOyQlQp0=
deploy:
  provider: heroku
  api_key:
    secure: lddhEXM4pKC4oZRrlTf+IcSVb9MyZy/mUXj1f1jfZtPlJTVBbGdi4NS70LABdTwo5fH4oDDYpTknMK+X/9K7kN981kbu/MIb0hf7bAO0NKbzaOpsLu4+1HUEXgdhvC7koaZf6pHHGEhKiJRbiw348ck+syEHfISX217q89eSXNitI4RKXJGa0PYgi2SZFKPJDdkTQA/XqatVW48n9fap7xh+CfAr1im9tjNncwSStxoJ7AtLgeitES6RYUftRdlZDTsIIGh800rJ19Fb+P0WUTuba8TIs9g4UyytRiXWBpPc/1p6tJqXaZ1kAcvts084n6tNae6ty8l0b26tEnkLWtNowwcJtGvNO4a6WpUNkoetqcXGyGU8AmHkkhUnsxw5yAJeVxDtat64JA52R9bo6DIE5qRchvmZNfTps3mnSjhWqxjzZGy18WNjnitBe+5p9jzkzOI97hb8zxMALO3eZwSO06Up15n3ce0nMAxroh52AoWma5ww7N8hC2aP6SdQc5FjJ25ueCkd/ZP4Piw8k8OCKy0CV3W+DstpNIvTjhzkF6qh/T4LK3rChLVMaPALvhDVwaUOZPu8HC3is16g/x2u3XkB5oSwJgC1Ora7JD+YTruXH2hktRBzyZEQjfCuwsOVXsMoT94K5IWOj1LlqMwV4Ws/957oAZESvgbB/3Q=
  app:
    feature1: player-sankey
